      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: >
            release
            --skip=publish
            --clean
            --config .goreleaser.${{ matrix.goos }}.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}